import fs from "fs";
import path from "path";
import shopify from "../utils/shopify.js";

const eventWriter = (config) => {
  const events = shopify.user.events || [];
  if (!events.length) {
    writeToApi();
    return;
  }

  const handles = new Set();
  let subscriptionsArray = [];
  for (const entry in events) {
    if (handles.has(events[entry].handle)) {
      throw new Error(`Duplicate event handle: ${events[entry].handle}`);
    }
    handles.add(events[entry].handle);

    const subscription = {
      topic: events[entry].topic,
      actions: events[entry].actions,
      uri: events[entry].uri.startsWith("/api/events/")
        ? `${process.env.SHOPIFY_APP_URL}${events[entry].uri}`
        : events[entry].uri,
      handle: events[entry].handle,
    };

    if (events[entry].triggers) {
      subscription.triggers = events[entry].triggers;
    }

    if (events[entry].query) {
      subscription.query = events[entry].query;
    }

    if (events[entry].query_filter) {
      subscription.query_filter = events[entry].query_filter;
    }

    subscriptionsArray.push(subscription);
  }

  config.events = {};
  config.events.api_version = "unstable"; //MARK:- At a later stage, once Events goes GA, update this to follow versioning with override support in `utils/shopify.js`
  config.events.subscription = [...subscriptionsArray];

  writeToApi();
};

const shopifyFilePath = path.join(process.cwd(), "utils", "shopify.js");
const eventsTopicFilePath = path.join(
  process.cwd(),
  "pages",
  "api",
  "events",
  "[...eventsTopic].js"
);

async function writeToApi() {
  try {
    const shopifyFileContent = fs.readFileSync(shopifyFilePath, "utf8");
    const eventImports = shopifyFileContent.match(
      /import .* from "\.\/events\/.*";/g
    );

    let eventsTopicFileContent = fs.readFileSync(eventsTopicFilePath, "utf8");

    const topComment = `/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * Head over to utils/shopify.js to create your events
 *  and write your event functions in utils/events.
 * To update this file, run \`npm run update:config\` or \`bun run update:config\`
 */\n\n`;

    // Remove the existing comment if it's already there
    eventsTopicFileContent = eventsTopicFileContent.replace(
      /\/\*\*[\s\S]*?\*\/\s*/,
      ""
    );

    // Start with the comment and shopify import
    let newFileContent =
      topComment + 'import shopify from "@/utils/shopify.js";\n';

    // Add new imports from event handlers
    if (eventImports) {
      eventImports.forEach((importStatement) => {
        const formattedImportStatement = importStatement.replace(
          "./events",
          "@/utils/events"
        );
        newFileContent += formattedImportStatement + "\n";
      });
    }

    // Get the rest of the file content after imports
    const mainContent = eventsTopicFileContent.replace(
      /^([\s\S]*?^import[^\n]*\n)+/m,
      ""
    );

    // Combine everything
    eventsTopicFileContent = newFileContent + mainContent;

    const events = shopify.user.events || [];

    // Generate the switch/case statement
    let switchCaseStatement = "switch (eventHandle) {\n";

    for (const entry of events) {
      if (entry.uri.startsWith("/api/events")) {
        const handlerName = entry.callback.name;
        switchCaseStatement += `  case "${entry.handle}":\n`;
        switchCaseStatement += `    await ${handlerName}(validateEvent.topic, shop, rawBody, webhookId, apiVersion, eventHandle);\n`;
        switchCaseStatement += `    break;\n`;
      }
    }
    switchCaseStatement += `  default:\n`;
    switchCaseStatement += `    throw new Error(\`Can't find a handler for \${eventHandle}\`);\n`;
    switchCaseStatement += "}\n";

    // Replace the existing switch/case statement
    const switchCaseRegex = /\/\/SWITCHCASE\n[\s\S]*?\/\/SWITCHCASE END/;
    eventsTopicFileContent = eventsTopicFileContent.replace(
      switchCaseRegex,
      `//SWITCHCASE\n${switchCaseStatement}//SWITCHCASE END`
    );

    fs.writeFileSync(eventsTopicFilePath, eventsTopicFileContent, "utf8");
  } catch (error) {
    console.error("Error writing to eventsTopic file:", error);
  }
}

export default eventWriter;
