/**
 * DO NOT EDIT THIS FILE DIRECTLY
 * Head over to utils/shopify.js to create your events
 *  and write your event functions in utils/events.
 * To update this file, run `npm run update:config` or `bun run update:config`
 */

import shopify from "@/utils/shopify.js";

async function buffer(readable) {
  const chunks = [];
  for await (const chunk of readable) {
    chunks.push(typeof chunk === "string" ? Buffer.from(chunk) : chunk);
  }
  return Buffer.concat(chunks);
}

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(400).send("It ain't POST mate.");
  }

  const topic = req.headers["shopify-topic"] || "";
  const shop = req.headers["shopify-shop-domain"] || "";
  const apiVersion = req.headers["shopify-api-version"] || "";
  const handle = req.headers["shopify-handle"] || "";
  const webhookId = req.headers["shopify-webhook-id"] || "";

  const buff = await buffer(req);
  const rawBody = buff.toString("utf8");

  try {
    const validateEvent = await shopify.webhooks.validate({
      rawBody: rawBody,
      rawRequest: req,
      rawResponse: res,
    });

    if (validateEvent.valid) {
    } else {
      return res.status(400).send({ error: true });
    }

    const eventHandle = validateEvent.handle || handle;

    //SWITCHCASE
    switch (eventHandle) {
      default:
        throw new Error(`Can't find a handler for ${eventHandle}`);
    }
    //SWITCHCASE END

    console.log(`--> Processed ${topic} from ${shop}`);
    return res.status(200).send({ message: "ok" });
  } catch (e) {
    console.error(
      `---> Error while processing events for ${shop} at ${topic} | ${e.message}`
    );

    if (!res.headersSent) {
      console.error("No headers sent");
    }
    return res.status(500).send({ message: "Error" });
  }
}

export const config = {
  api: {
    bodyParser: false,
  },
};
